### ISSUE TITLE
Placeholder de la incidencia no desaparece

### ISSUE THREAD

**Issue by anasmez** [CityReportCUSL/CityReportAPP#3]
El placeholder no desaparece en el primer click y siendo quisquillosos, hay 4 puntos suspensivos en vez de 3.

**Comment by VictorNarov** [comment]
¡Hola @anasmez! Primeramente gracias por reportar el issue.
Se ha corregido en este [commit ](https://github.com/CityReportCUSL/CityReportAPP/commit/aaf644fab18112f4960322419ec943b26fd34a04)
cambiando el onClickListener del editText a un onTouchListener:

```        //Eliminar el texto cuando clique en el área del texto de la descripción
        textoDesc.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (MotionEvent.ACTION_UP == event.getAction()) {
                    if (!primerclick) {
                        textoDesc.setText("");
                        primerclick = true;
                    }
                }
                return false;

            }

        });
```

**Comment by anasmez** [comment]
De nada, @Narovik. Estaré atento al proyecto porque me parece muy interesante el concepto.
