### ISSUE TITLE
Mensaje agradecimiento no sale como en la foto

### ISSUE THREAD

**Issue by anasmez** [CityReportCUSL/CityReportAPP#4]
Solo sale un pequeño pop up dando las gracias y ya y no como en la foto que es lo que pone en el blog que debería salir.
![imagen](https://user-images.githubusercontent.com/23346094/71963670-70127980-31fc-11ea-9822-3dd57b881c77.png)

**Comment by VictorNarov** [comment]
Se ha corregido en este [commit ](https://github.com/CityReportCUSL/CityReportAPP/commit/aaf644fab18112f4960322419ec943b26fd34a04)
